### ISSUE TITLE
Parse the Bard's plays

### ISSUE THREAD

**Issue by thachhoang** [IsabellaS09/truecrimeviewer#3]
https://www.gutenberg.org/ebooks/100

**Comment by IsabellaS09** [comment]
Im trying to figure out the best way to parse the document/finding appropriate quotes? Should I just not care about meaning?

**Comment by thachhoang** [comment]
I'm fine with just getting random lines of dialogue. Parsing the meaning is harder and could be a stretch goal.

**Comment by IsabellaS09** [comment]
okay, what should the character number limit be?

**Comment by thachhoang** [comment]
It probably depends on the size of your dialogue box. Example:

```
A: Hello.
B: This is a long line of text. It won't fit in the box.
```

becomes:

```
A: Hello.
B: This is a long line of text.
B: It won't fit in the box.
```
