### ISSUE TITLE
We should set up the basic window for now

### ISSUE THREAD

**Issue by IsabellaS09** [IsabellaS09/truecrimeviewer#8]
As of now when you click on the markers, all you get is the description, we should set it up so we have at least the basic window with scene.

**Comment by thachhoang** [comment]
You should pull. On master you get the scene and the vehicle.

**Comment by thachhoang** [comment]
I should be online around 9pm. Here are the things we still need to do, I'm too lazy to ticket them yet.
https://github.com/IsabellaS09/truecrimeviewer/wiki/Notes

**Comment by IsabellaS09** [comment]
Its not working in the demo though.

**Comment by thachhoang** [comment]
@IsabellaS09 @jbccollins Demo updated, QA when you have the chance.
