### ISSUE TITLE
Gutenberg Website Request Limits

### ISSUE THREAD

**Issue by IsabellaS09** [IsabellaS09/truecrimeviewer#9]
I have the script set up to work correctly, and get the quotes however the code is making several requests to gutenberg's website and they have request limits and I've been blocked. If you could look over my code and see if anything is causing it(in master) and then rerun the code to populate the quotes.json that would be helpful.

**Comment by thachhoang** [comment]
I committed that text file to master, so you can read from it instead of pulling from the PG website. You should make a pull request for new changes too, so I can avoid conflicts.

**Comment by thachhoang** [comment]
`get_chat()` is called for every event, and script loads 50000 by default, which is why PG blocks you.

**Comment by IsabellaS09** [comment]
Okay, cool thanks I'll work on the text box

**Comment by IsabellaS09** [comment]
@thachhoang I need you to rerun the script, and just remove the call the get_chat in the get_violations method, the quotes.json is empty right now

**Comment by thachhoang** [comment]
You can read from data/shakespeare.txt instead of using requests. BTW @jbccollins and I are on chat right now, hop on when you can.

**Comment by IsabellaS09** [comment]
What chat are you on?

**Comment by IsabellaS09** [comment]
@thachhoang

**Comment by thachhoang** [comment]
Emailed you at the school account.
